### PR TITLE
Fix customer cart + menu

### LINKED ISSUE #64: KX: update customers menu + images
- [x] Make customer cart auto apply rpromos (apply upon subtotal change instead of having to press button.)
- [x] Fix customers menu + images

### PR DESCRIPTION
**Pull request by kxyoke**
Fixes #64 
- [x] cart (incl auto apply res promo)
- [x] menu and images (incl availability)

### CODE REVIEW

**Comment by kxyoke** [comment]
@ShuTingY the cart atm overwrites the original item in cart when we add that item from the restaurant. Is this expected behaviour?

**Comment by kxyoke** [comment]
Might need to check if the availability shows correctly

**Comment by ShuTingY** [comment]
> @ShuTingY the cart atm overwrites the original item in cart when we add that item from the restaurant. Is this expected behaviour?

Yes that is what I design it to be.
Overwrite the qty if the item is in the cart
add new if it is not in the cart

**Comment by kxyoke** [comment]
> > @ShuTingY the cart atm overwrites the original item in cart when we add that item from the restaurant. Is this expected behaviour?
> 
> Yes that is what I design it to be.
> Overwrite the qty if the item is in the cart
> add new if it is not in the cart

ok will explain in functionalities also

**Pull request merged**
